// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/club-website-variants/Crisp.tsx": () => import("../components/mockups/club-website-variants/Crisp.tsx"),
  "./components/mockups/club-website-variants/Elevated.tsx": () => import("../components/mockups/club-website-variants/Elevated.tsx")
};
